SELECT CASE WHEN BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker) THEN 'OLDEST' WHEN BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM worker) THEN 'YOUNGEST'
 END AS TYPE, NAME, BIRTHDAY FROM worker WHERE BIRTHDAY IN (SELECT MIN(BIRTHDAY) FROM worker UNION SELECT MAX(BIRTHDAY) FROM worker);
